---
services:
  mymulti:
    image: myapp111
    ports:
      - "30016:8889"
    restart: always
#     volumes:
#       - ".:/app"
#     depends_on:
#       - db

#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_PASSWORD: password
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

# volumes:
#   pgdata:
